language: java
script:
  - ./gradlew build -s
  - ls -al build/libs
  - java -cp build/libs/whisk.jar:$(find $JAVA_HOME -name 'tools.jar') org.whisk.MainKt /:main
  - cp whisk-out/jar/whisk.jar .
  - java -cp main.jar:$(find $JAVA_HOME -name 'tools.jar') org.whisk.MainKt /:main