language: java
jdk: openjdk8
script:
  - ./gradlew build -s
  - ls -al build/libs
  - java -jar build/libs/whisk.jar test
  - cp whisk-out/jar/whisk.jar .
  - rm -rf whisk-out
  - java -jar whisk.jar test