root_artifacts=["com.google.dagger:dagger-compiler:2.22.1"]
[[maven_artifact]]
name="com.google.code.findbugs_jsr305"
url="https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar"
sha1="40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf"

[[maven_artifact]]
name="com.google.dagger_dagger-compiler"
url="https://repo.maven.apache.org/maven2/com/google/dagger/dagger-compiler/2.22.1/dagger-compiler-2.22.1.jar"
sha1="483b9dc35817e8f0b771254e85507ffdc66d4a42"

[[maven_artifact]]
name="com.google.dagger_dagger-producers"
url="https://repo.maven.apache.org/maven2/com/google/dagger/dagger-producers/2.22.1/dagger-producers-2.22.1.jar"
sha1="1cc1e9db080c1c0a5ae55460ef8536efe1e76162"

[[maven_artifact]]
name="com.google.dagger_dagger-spi"
url="https://repo.maven.apache.org/maven2/com/google/dagger/dagger-spi/2.22.1/dagger-spi-2.22.1.jar"
sha1="f8e8d8f85b8cc62c027eb7cd3caec8519e985e12"

[[maven_artifact]]
name="com.google.dagger_dagger"
url="https://repo.maven.apache.org/maven2/com/google/dagger/dagger/2.22.1/dagger-2.22.1.jar"
sha1="b5df4215f441908335e482f869bbf90c529eeaaf"

[[maven_artifact]]
name="com.google.errorprone_error_prone_annotations"
url="https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar"
sha1="39b109f2cd352b2d71b52a3b5a1a9850e1dc304b"

[[maven_artifact]]
name="com.google.errorprone_javac-shaded"
url="https://repo.maven.apache.org/maven2/com/google/errorprone/javac-shaded/9-dev-r4023-3/javac-shaded-9-dev-r4023-3.jar"
sha1="72b688efd290280a0afde5f9892b0fde6f362d1d"

[[maven_artifact]]
name="com.google.googlejavaformat_google-java-format"
url="https://repo.maven.apache.org/maven2/com/google/googlejavaformat/google-java-format/1.5/google-java-format-1.5.jar"
sha1="fba7f130d29061d2d2ea384b4880c10cae92ef73"

[[maven_artifact]]
name="com.google.guava_guava"
url="https://repo.maven.apache.org/maven2/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar"
sha1="7319c34fa5866a85b6bad445adad69d402323129"

[[maven_artifact]]
name="com.google.j2objc_j2objc-annotations"
url="https://repo.maven.apache.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar"
sha1="ed28ded51a8b1c6b112568def5f4b455e6809019"

[[maven_artifact]]
name="com.squareup_javapoet"
url="https://repo.maven.apache.org/maven2/com/squareup/javapoet/1.11.1/javapoet-1.11.1.jar"
sha1="210e69f58dfa76c5529a303913b4a30c2bfeb76b"

[[maven_artifact]]
name="javax.annotation_jsr250-api"
url="https://repo.maven.apache.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar"
sha1="5025422767732a1ab45d93abfea846513d742dcf"

[[maven_artifact]]
name="javax.inject_javax.inject"
url="https://repo.maven.apache.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar"
sha1="6975da39a7040257bd51d21a231b76c915872d38"

[[maven_artifact]]
name="org.checkerframework_checker-compat-qual"
url="https://repo.maven.apache.org/maven2/org/checkerframework/checker-compat-qual/2.5.3/checker-compat-qual-2.5.3.jar"
sha1="045f92d2e0676d05ae9297269b8268f93a875d4a"

[[maven_artifact]]
name="org.codehaus.mojo_animal-sniffer-annotations"
url="https://repo.maven.apache.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar"
sha1="775b7e22fb10026eed3f86e8dc556dfafe35f2d5"

