root_artifacts=["com.google.dagger:dagger-compiler:2.22.1"]
[[maven_artifact]]
name="com.google.code.findbugs_jsr305"
url="http://central.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar"
sha1=""

[[maven_artifact]]
name="com.google.dagger_dagger-compiler"
url="http://central.maven.org/maven2/com/google/dagger/dagger-compiler/2.22.1/dagger-compiler-2.22.1.jar"
sha1=""

[[maven_artifact]]
name="com.google.dagger_dagger-producers"
url="http://central.maven.org/maven2/com/google/dagger/dagger-producers/2.22.1/dagger-producers-2.22.1.jar"
sha1=""

[[maven_artifact]]
name="com.google.dagger_dagger-spi"
url="http://central.maven.org/maven2/com/google/dagger/dagger-spi/2.22.1/dagger-spi-2.22.1.jar"
sha1=""

[[maven_artifact]]
name="com.google.dagger_dagger"
url="http://central.maven.org/maven2/com/google/dagger/dagger/2.22.1/dagger-2.22.1.jar"
sha1=""

[[maven_artifact]]
name="com.google.errorprone_error_prone_annotations"
url="http://central.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar"
sha1=""

[[maven_artifact]]
name="com.google.errorprone_javac-shaded"
url="http://central.maven.org/maven2/com/google/errorprone/javac-shaded/9-dev-r4023-3/javac-shaded-9-dev-r4023-3.jar"
sha1=""

[[maven_artifact]]
name="com.google.googlejavaformat_google-java-format"
url="http://central.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.5/google-java-format-1.5.jar"
sha1=""

[[maven_artifact]]
name="com.google.guava_guava"
url="http://central.maven.org/maven2/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar"
sha1=""

[[maven_artifact]]
name="com.google.j2objc_j2objc-annotations"
url="http://central.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar"
sha1=""

[[maven_artifact]]
name="com.squareup_javapoet"
url="http://central.maven.org/maven2/com/squareup/javapoet/1.11.1/javapoet-1.11.1.jar"
sha1=""

[[maven_artifact]]
name="javax.annotation_jsr250-api"
url="http://central.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar"
sha1=""

[[maven_artifact]]
name="javax.inject_javax.inject"
url="http://central.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar"
sha1=""

[[maven_artifact]]
name="org.checkerframework_checker-compat-qual"
url="http://central.maven.org/maven2/org/checkerframework/checker-compat-qual/2.5.3/checker-compat-qual-2.5.3.jar"
sha1=""

[[maven_artifact]]
name="org.codehaus.mojo_animal-sniffer-annotations"
url="http://central.maven.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar"
sha1=""

