[[java_binary]]
name="main"
files=[":whisk-core", ":maven-deps", "/test:whisk-test"]
main_class = "org.whisk.MainKt"

[[kotlin_compile]]
name="whisk-core"
cp=[":tomlj", ":antlr4", ":annotations", ":kotlin-stdlib", ":kotlin-compiler", ":kotlin-stdlib-common", ":kotlin-stdlib-jdk7", ":kotlin-stdlib-jdk8", ":trove4j",
    ":log4j2-api", ":log4j2-core", ":maven-deps", ":junit4", ":hamcrest", ":kotlin-reflect"]
exported_deps=[":tomlj", ":antlr4", ":annotations", ":kotlin-compiler", ":kotlin-stdlib", ":kotlin-stdlib-common", ":kotlin-stdlib-jdk7", ":kotlin-stdlib-jdk8", ":trove4j",
    ":log4j2-api", ":log4j2-core", ":junit4", ":hamcrest", ":kap"]
kapt_deps=[":tools", ":kap", ":dagger"]

[[prebuilt_jar]]
name="tomlj"
binary_jar="lib/tomlj-1.0.0.jar"

[[prebuilt_jar]]
name="antlr4"
binary_jar="lib/antlr4-runtime-4.7.2.jar"

[[prebuilt_jar]]
name="annotations"
binary_jar="lib/annotations-13.0.jar"

[[remote_file]]
name="kotlin-compiler"
url="http://central.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.31/kotlin-compiler-embeddable-1.3.31.jar"
sha1=""

[[prebuilt_jar]]
name="kotlin-stdlib"
binary_jar="lib/kotlin-stdlib-1.3.31.jar"

[[prebuilt_jar]]
name="tools"
binary_jar="/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar"

[[prebuilt_jar]]
name="kotlin-stdlib-common"
binary_jar="lib/kotlin-stdlib-common-1.3.31.jar"

[[prebuilt_jar]]
name="kotlin-stdlib-jdk7"
binary_jar="lib/kotlin-stdlib-jdk7-1.3.31.jar"

[[prebuilt_jar]]
name="kotlin-stdlib-jdk8"
binary_jar="lib/kotlin-stdlib-jdk8-1.3.31.jar"

[[remote_file]]
name="trove4j"
url="http://central.maven.org/maven2/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar"
sha1=""

[[remote_file]]
name="log4j2-api"
url="http://central.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar"
sha1=""

[[remote_file]]
name="log4j2-core"
url="http://central.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar"
sha1=""

[[maven_library]]
name="maven-deps"
artifacts=["org.apache.maven:maven-resolver-provider:3.6.1",
           "org.apache.maven.resolver:maven-resolver-transport-http:1.3.3",
           "org.apache.maven.resolver:maven-resolver-connector-basic:1.3.3",
           "com.google.dagger:dagger:2.22.1"]

[[maven_library]]
name="dagger"
artifacts=["com.google.dagger:dagger-compiler:2.22.1"]

[[remote_file]]
name="junit4"
url="http://central.maven.org/maven2/junit/junit/4.12/junit-4.12.jar"
sha1=""

[[remote_file]]
name="hamcrest"
url="http://central.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"
sha1=""

[[remote_file]]
name="kap"
url="http://central.maven.org/maven2/org/jetbrains/kotlin/kotlin-annotation-processing-embeddable/1.3.31/kotlin-annotation-processing-embeddable-1.3.31.jar"
sha1=""

[[remote_file]]
name="kotlin-reflect"
url="http://central.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.31/kotlin-reflect-1.3.31.jar"
sha1=""
